cookie:
  expiry_days: 30
  key: some_signature_key_for_diploma
  name: bug_classifier_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Денис (Адмін)
      password: $2b$12$SNEW1ME5V3zNutgGHFn8ru1DZcgSBEFzW4S/2zSR5iN5U2Me/l9kO
    engineer:
      email: engineer@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Світлана (Інженер)
      password: $2b$12$GMUfE4Ta9Cdlm4H46.9eMOZ5VOF/aUaVHTi6c2dVUfovEJTTs/dKm
preauthorized:
  emails: []
